export const Screens = {
    MainScreen: 'Main Screen',
    SlideImageScreen: 'Slide Image Screen',
    Image3DFlipScreen: 'Image 3D Flip Screen',
    Card3DScreen: 'Card 3D Screen',
    AnalogClockScreen: 'Analog Clock Screen',
    AddToCartScreen: 'Add To Cart Screen',
    ImageSliderScreen: 'Image Slider Screen',
    ImageSlider1Screen: 'Image Slider 1 Screen',
    ImageSlider2Screen: 'Image Slider 2 Screen',
    ImageSlider3Screen: 'Image Slider 3 Screen',
    DraggableScreen: 'Draggable Screen',
    ShapeImageScreen: 'Shape Image Screen',
    ToggleButtonScreen: 'Toggle Button Screen',
    StoryScreen: 'Story Screen',
    ImageCarouselScreen: 'Image Carousel Screen',
    ImageCarousel1Screen: 'Image Carousel 1 Screen',
    ImageCarousel2Screen: 'Image Carousel 2 Screen',
    ImageCarousel3Screen: 'Image Carousel 3 Screen',
    ImageCarousel4Screen: 'Image Carousel 4 Screen',
}